config/routes.rb
require 'sidekiq/web'

Aer::Application.routes.draw do
  use_doorkeeper

  devise_for :drivers, controllers: { registrations: "driver/registrations" }
  devise_for :users

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Aer::API => '/api', as: 'api'

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
    resources :sms_messages, only: [:new, :create, :destroy] do
      member do
        post :resend
      end
      collection do
        post :clear_pending
      end
    end
  end

  authenticate :driver do
    resources :teams, only: [:index] do
      post "select", on: :member
    end
    resources :drivers, only: [:show] do
      collection do
        get :autocomplete
      end
    end
    resource :team, except: [:destroy]
    resources :cars
    resources :registrations, only: [:create, :show, :destroy, :update] do
      resources :payments, only: [:create]
      resources :drivers, only: [:index, :create, :destroy], module: 'registrations'
      resources :reservables, only: [:index, :show] do
        resource :reservation, only: [:create, :destroy]
      end
    end
  end

  resources :drivers, only: [:index] do
    member do
      get :barcode
    end
  end

  resources :seasons, only: [] do
    resources :results, only: [:index]
  end

  resources :events, only: [:index] do
    get :teams
    get :stops
    resources :laptimes, only: [:index]
    resources :races, only: [:index]
    resources :results, only: [:index]
    resources :reservables, only: [:index, :show]
    post :registrations

    authenticate :user do
      resources :driver_registrations, only: [:index]
    end
  end

  resources :races, only: [] do
    resources :unknown_drivers, only: [:index]
    resources :results, only: [:index, :create] do
      collection do
        get :grid
        post :grid, action: 'update_grid'
        get :preview
        post :preview, action: 'update_preview'
        post :generate
      end
    end
  end

  resources :scans, only: [:update]

  authenticate :user do
    resources :registrations, only: [] do
      resources :scans, only: [:new]
    end
  end

  resources :scans, only: [:create, :show] do
    post :analyze, on: :member
    post :mock_pit, on: :member
    post :violation, on: :member
  end

  resources :rfid_reads, only: [:create, :index, :show]

  get '/live', to: 'live#show', as: 'live'

  get '/scan/:event/:pit/:car/:driver', :to => 'scan#create'
  post '/scan/:event/:pit/:car/:driver', :to => 'scan#create'

  get '/cars/:id/barcode', :to => 'car#barcode'
  get '/qualifying', :to => 'qualifying#index'

  get '/orbits/export', :to => 'orbits#export'

  post '/rfidtest', to: 'rfidtests#create'

  root to: redirect("/team")
end

app/models/sms_message.rb
# create_table :sms_messages, force: :cascade do |t|
#   t.string   :number,        limit: 255
#   t.string   :message,       limit: 255
#   t.datetime :sent_at
#   t.integer  :resource_id,   limit: 4
#   t.string   :resource_type, limit: 255
#   t.datetime :created_at
#   t.datetime :updated_at
#   t.integer  :driver_id,     limit: 4
#   t.datetime :read_at
# end
#
# add_index :sms_messages, [:driver_id, :read_at], name: :index_sms_messages_on_driver_id_and_read_at, using: :btree

class SmsMessage < ActiveRecord::Base
  belongs_to :resource, polymorphic: true
  belongs_to :driver

  validates :driver, presence: true

  after_create :send_sms_message

  scope :pending, ->{ where(sent_at: nil) }
  scope :unread,  ->{ where(read_at: nil) }

  def send_sms_message
    if driver.notifications_enabled?
      notification = {
        title: "New Message from AER",
        body: "You have received a new message from AER.",
        sound: 'default'  # Required for sounds
      }

      data = {
        messageTitle: self.created_at.to_s,
        messageBody: self.message,
        messageId: self.id
      }

      $fcm.send([driver.fcm_token],
                notification: notification,
                data: data,
                priority: "high",
                "content_available": true)

      touch(:sent_at)
    elsif self.number.present?
      SmsMessengerJob.perform_async(self.id)
    end
  end

  def resend
    send_sms_message_job
  end

  def title
    (sent_at || created_at).in_time_zone("America/New_York").strftime("%b %e, %Y %l:%M%p")
  end

  def recipient
    if resource.present?
      "#{resource} (#{driver})"
    else
      "#{driver}"
    end
  end
end

app/controllers/sms_messages_controller.rb
class SmsMessagesController < ApplicationController
  def new
    # Sms Messages can be sent to:
    #  - Everyone
    #  - Specific Driver (autocomplete. Uncheck a box if you want to search entire db)
    #  - All drivers attached to a registration (Specify car #)
    #
    @messages    = SmsMessage.order("(sent_at IS NULL) DESC, sent_at DESC").first(100)
    @drivers     = ContactSerializer.serialize(Driver.where("cell_phone IS NOT NULL").order("last_name ASC, first_name ASC").all)
    @event       = Event.current || Event.next
    @sms_message = SmsMessage.new

    if @event
      @registered_drivers = ContactSerializer.serialize(@event.driver_registrations)
      @registrations = ContactSerializer.serialize(@event.registrations)
      @events = { id: @event.id, name: "All Registered Drivers at #{@event.to_s}" }
    end
  end

  def destroy
    SmsMessage.pending.find(params[:id]).destroy
    flash[:success] = "Message erased from queue"

    redirect_to new_sms_message_path
  end

  def clear_pending
    SmsMessage.pending.destroy_all
    flash[:success] = "Pending messages cleared"

    redirect_to new_sms_message_path
  end

  def resend
    if SmsMessage.find(params[:id]).resend
      flash[:success] = "Message will be sent"
    else
      flash[:error] = "Sending error"
    end
    redirect_to new_sms_message_path
  end

  def create
    messenger = SmsMessenger.new(sms_message_params)
    if messenger.send
      flash[:success] = "#{messenger.send_count} message(s) will be delivered"
    else
      flash[:error] = "Error: #{messenger.error_message}"
    end

    redirect_to new_sms_message_path
  end

  private
  def sms_message_params
    params.require(:sms_message).permit(:resource_type, :resource_id, :message)
  end
end

app/views/sms_messages/new.html.slim
h1.ui.header SMS Messages
.right.floated.content
  = link_to "Clear pending", clear_pending_sms_messages_path, class: 'ui button', method: :post
.ui.segment
  .ui.relaxed.divided.list(style="height: 300px; overflow-y: scroll")
    - @messages.each do |message|
      .item
        .right.floated.content
          - if message.sent_at.nil?
            em
              = link_to "pending", resend_sms_message_path(message), method: :post
            = " "
            = link_to "[x]", sms_message_path(message), method: :delete
          - else
            =message.sent_at.in_time_zone("America/New_York")
        .content
          .header=message.recipient
          =message.message

.ui.segment
  - if @event
    h2.ui.header
      .content= @event.name
      .sub.header= "#{@event.start_date.to_s(:long)} to #{@event.stop_date.to_s(:long)}"

    p The event above is used to fill teams and drivers below

  .ui.inverted.segment
    = form_for @sms_message, html: { class: 'ui inverted form'} do |f|
      #resource_type.inline.fields
        label.ui.label(for="resource_type") Deliver to
        - if @event
          .field
            .ui.radio.checkbox
              = f.radio_button :resource_type, 'Event'
              label #{@event.name}

          .field
            .ui.radio.checkbox
              = f.radio_button :resource_type, 'Registration'
              label Registration/Team

          .field
            .ui.radio.checkbox
              = f.radio_button :resource_type, 'DriverRegistration'
              label Registered Driver

        .field
          .ui.radio.checkbox
            = f.radio_button :resource_type, 'Driver'
            label Driver

      #recipient_search.field(style="display: hidden")
        label Recipient
        .ui.fluid.search.selection.dropdown.manual
          = f.hidden_field :resource_id
          = semantic_icon 'dropdown'
          .default.text Select Recipient...
          #recipients.menu

      .field
        label.ui.required Message
        = f.text_field :message, class: 'ui large input'

      = submit_tag 'Send', class: 'ui blue button'

javascript:
  ContactList = { Driver: #{{@drivers.to_json}}, Event: [#{{@events.to_json}}], Registration: #{{@registrations.to_json}}, DriverRegistration: #{{@registered_drivers.to_json}} }

  $('#recipient_search .dropdown').dropdown({
    action: 'activate',
    onChange: function(value) {
    console.log(value);
      var $resourceId = $('#sms_message_resource_id');

      $resourceId.val(value);
    }
  });

  $('#resource_type .checkbox').checkbox({
    onChecked: function() {
      var resource_type = $(this).val();
      var recipients    = $('#recipients');
      var dropdown      = $('#recipient_search .dropdown');

      recipients.html('');
      dropdown.dropdown('clear');

      $.each(ContactList[resource_type], function(i, item) {
        var opt = $('<div class="item">');
        opt.attr('data-value', item.id);
        opt.text(item.name);

        recipients.append(opt);
      });

      $('#recipient_search').show();

      if (ContactList[resource_type].length == 1) {
        dropdown.dropdown('refresh');
        dropdown.dropdown('set selected', ContactList[resource_type][0].id);
      }
    }
  });