config/routes.rb
require 'sidekiq/web'

Aer::Application.routes.draw do
  use_doorkeeper

  devise_for :drivers, controllers: { registrations: "driver/registrations" }
  devise_for :users

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Aer::API => '/api', as: 'api'

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
    resources :sms_messages, only: [:new, :create, :destroy] do
      member do
        post :resend
      end
      collection do
        post :clear_pending
      end
    end
  end

  authenticate :driver do
    resources :teams, only: [:index] do
      post "select", on: :member
    end
    resources :drivers, only: [:show] do
      collection do
        get :autocomplete
      end
    end
    resource :team, except: [:destroy]
    resources :cars
    resources :registrations, only: [:create, :show, :destroy, :update] do
      resources :payments, only: [:create]
      resources :drivers, only: [:index, :create, :destroy], module: 'registrations'
      resources :reservables, only: [:index, :show] do
        resource :reservation, only: [:create, :destroy]
      end
    end
  end

  resources :drivers, only: [:index] do
    member do
      get :barcode
    end
  end

  resources :seasons, only: [] do
    resources :results, only: [:index]
  end

  resources :events, only: [:index] do
    get :teams
    get :stops
    resources :laptimes, only: [:index]
    resources :races, only: [:index]
    resources :results, only: [:index]
    resources :reservables, only: [:index, :show]
    post :registrations

    authenticate :user do
      resources :driver_registrations, only: [:index]
    end
  end

  resources :races, only: [] do
    resources :unknown_drivers, only: [:index]
    resources :results, only: [:index, :create] do
      collection do
        get :grid
        post :grid, action: 'update_grid'
        get :preview
        post :preview, action: 'update_preview'
        post :generate
      end
    end
  end

  resources :scans, only: [:update]

  authenticate :user do
    resources :registrations, only: [] do
      resources :scans, only: [:new]
    end
  end

  resources :scans, only: [:create, :show] do
    post :analyze, on: :member
    post :mock_pit, on: :member
    post :violation, on: :member
  end

  resources :rfid_reads, only: [:create, :index, :show]

  get '/live', to: 'live#show', as: 'live'

  get '/scan/:event/:pit/:car/:driver', :to => 'scan#create'
  post '/scan/:event/:pit/:car/:driver', :to => 'scan#create'

  get '/cars/:id/barcode', :to => 'car#barcode'
  get '/qualifying', :to => 'qualifying#index'

  get '/orbits/export', :to => 'orbits#export'

  post '/rfidtest', to: 'rfidtests#create'

  root to: redirect("/team")
end

app/models/event.rb
# create_table :events, force: :cascade do |t|
#   t.string   :track,               limit: 255
#   t.date     :start_date
#   t.date     :stop_date
#   t.datetime :created_at
#   t.datetime :updated_at
#   t.string   :abbr,                limit: 255
#   t.float    :track_length,        limit: 24
#   t.string   :supplemental_charge, limit: 255
#   t.text     :promo_content,       limit: 65535
#   t.integer  :season_id,           limit: 4
#   t.integer  :capacity,            limit: 4,     default: 50
#   t.integer  :supplemental_limit,  limit: 4,     default: 50
#   t.integer  :price_in_cents,      limit: 4
# end
#
# add_index :events, [:abbr], name: :index_events_on_abbr, using: :btree

class Event < ActiveRecord::Base
  extend FriendlyId

  @@current_event = nil

  has_paper_trail

  friendly_id :abbr

  validates_presence_of :abbr, :track_length
  validates_uniqueness_of :abbr

  belongs_to :season

  has_many :registrations
  has_many :races, -> { order(:start_time) }, dependent: :destroy
  has_many :urls, as: :attached_to

  has_many :cars, through: :registrations
  has_many :payments, through: :registrations
  has_many :scans, through: :registrations
  has_many :driver_registrations, through: :registrations
  has_many :reservable_items

  validates :start_date, :stop_date, presence: true
  validates :season_id, presence: true
  validates :price_in_cents, presence: true

  scope :for_season, ->(season = Season.current) { where(season: season) }
  scope :registerable, -> { where("stop_date >= ?", Date.today) }
  scope :upcoming, ->{ where("start_date > ?", Date.today) }

  default_scope { order(start_date: :asc) }

  before_validation :assign_season_and_price, on: :create

  after_save :create_races!, on: :create

  def self.current
    if @@current_event.nil?
      where("start_date <= ? AND stop_date >= ?", Date.tomorrow, Date.today).first
    elsif @@current_event.is_a?(Event)
      @@current_event
    end
  end

  def self.current_or_next
    self.current || self.next
  end

  def self.next
    upcoming.first
  end

  def sold_out?
    self.registrations.ready.count >= self.capacity
  end

  def time_zone
    "America/New_York"
  end

  def create_races!
    if races.count == 0 and self.start_date.friday?
      friday   = self.start_date.to_time.in_time_zone(self.time_zone)
      saturday = friday   + 1.day
      sunday   = saturday + 1.day

      friday_start = friday.change(hour: 13)
      friday_end   = friday.change(hour: 19, min: 50)

      sat_start = saturday.change(hour: 8,  min: 30) # Allow time for grid scan-in
      sat_end   = saturday.change(hour: 18, min: 30)

      sun_start = sunday.change(hour: 8, min: 30)
      sun_end   = sunday.change(hour: 18, min: 30)

      # Friday Qualifying
      self.races.create(name: "Qualifying", start_time: friday_start, end_time: friday_end, qualifying: true)

      # Saturday
      self.races.create(name: "Saturday Race", start_time: sat_start, end_time: sat_end)

      # Sunday
      self.races.create(name: "Sunday Race", start_time: sun_start, end_time: sun_end)
    end
  end

  def laptimes_csv_file
    Rails.root.join("public/laptimes/#{friendly_id}.csv")
  end

  def laptimes_csv_file_exists?
    File.exists?(laptimes_csv_file)
  end

  def generate_laptimes!
    laptimes = LapTime.where(event_id: id).all
    headers = LapTime.csv_headers

    CSV.open(laptimes_csv_file, 'w') do |csv|
      csv << headers
      laptimes.each do |laptime|
        csv << laptime.csv_values
      end
    end
  end

  def drivers
    teams = cars.map(&:team)
    teams.uniq!

    teams.map(&:drivers).flatten
  end

  def upcoming?
    self.start_date >= Date.today
  end

  def past?
    !upcoming?
  end

  def current?
    self.start_date <= Date.today && self.stop_date >= Date.today
  end

  def name
    self.to_s
  end

  def to_s
    "#{self.track} (#{self.start_date})"
  end

  def allows_supplemental_charge?
    self.supplemental_charge.present? &&
      registrations.where(accepts_supplemental_charge: true).count < supplemental_limit
  end

  def assign_class(car_numbers:, car_class:)
    Registration.transaction do
      car_numbers.each do |car_number|
        registrations.by_car_number(car_number).update_attributes!(car_class: car_class)
      end
    end
  end

  def overall_winners
    results = races.map { |race| race.results.sorted }.flatten

    # {
    #   'Daytona' => [{
    #       total: 42,
    #       results: [#<Result "Saturday">, #<Result "Sunday">],
    #       car_id: 31,
    #       team: #<Team "Rally Baby">
    #       },
    #     ]
    # }

    winners = {}

    results.each do |result|
      if winners[result.car_class].nil?
        winners[result.car_class] = []
      end

      already_a_winner = false # Racing is serious business. Not everyone is a winner.

      winners[result.car_class].each do |winner|
        if winner[:car_id] == result.car.id
          winner[:results] << result
          winner[:total] += result.points_with_adjustments

          already_a_winner = true
        end
      end

      if !already_a_winner
        winner = {
            results: [result],
            registration: result.registration,
            car_id: result.car.id,
            team: result.team,
            total: result.points_with_adjustments
          }

        winners[result.car_class] << winner
      end
    end

    winners
  end

  def pretty_overall_winners
    pretty_winners = {}

    overall_winners.each_pair do |car_class, winners|
      if pretty_winners[car_class].nil?
        pretty_winners[car_class] = []
      end
      winners.each do |winner|
        pretty_winner = {
          total: winner[:total],
          car: "##{winner[:registration].car_number} #{winner[:team]}"
        }

        pretty_winners[car_class] << pretty_winner
      end

      pretty_winners[car_class].sort_by! { |pw| pw[:total] }.reverse!

      # Need to put in code for tie breakers.
      # Teams with a tie are sorted with the best finish on Sunday coming first
    end

    pretty_winners
  end

  def assign_season_and_price
    self.season         ||= Season.current
    self.price_in_cents ||= self.season.event_price_in_cents
  end

  rails_admin do
    configure :drivers do
      visible false

      pretty_value do
        bindings[:object].drivers.map(&:to_s).join(",<br> ").html_safe
      end
    end

    configure :driver_emails do
      formatted_value { "Driver emails" }

      visible false

      pretty_value do
        bindings[:object].drivers.map(&:mailchimp_csv).join("<br> ").html_safe
      end
    end

    list do
      filters [:season_id]

      field :season_id, :enum do
        filterable true

        enum { Season.select(:id).all }
      end

      field :track
      field :abbr
      field :track_length
      field :start_date
      field :stop_date
    end

    show do
      field :season
      field :track
      field :abbr
      field :track_length
      field :start_date
      field :stop_date
      field :drivers
      field :driver_emails
      field :promo_content
    end

    edit do
      field :season
      field :track
      field :abbr
      field :track_length
      field :start_date
      field :stop_date
      field :supplemental_charge
      field :promo_content
      field :capacity
      field :supplemental_limit
      field :urls
      field :price_in_cents
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @seasons = Season.all
    @year = params[:year] || Season.current.year
    @events = Event.for_season(Season[@year])
  end

  def teams
    @event = find_event
    @registrations = @event.registrations.expected_at_event.order_by_car_number
  end

  def stops
    @event = find_event
    @registrations = @event.registrations.expected_at_event.order_by_car_number
  end

  def registrations
    if current_user.present?

      update = []
      params[:registrations].each_pair do |id, attribs|
        Registration.where(id: id).update_all(car_class: attribs["car_class"], verified: attribs["verified"].to_s == 'true')
      end
      flash[:success] = "Car classes assigned"
    end
    redirect_to event_teams_path(find_event)
  end

  private
  def find_event
    Event.friendly.find(params[:event_id])
  end
end

app/views/events/index.html.slim
h1.ui.block.header
  = semantic_icon('large circular invertered calendar')
  .content
    | Event list
    .sub.header
      | All events for #{@year}

.ui.horizontal.list
  - @seasons.each do |season|
    a.ui.button.basic(href="#{events_path(year: season.year)}" class="#{"active" if @year == season.year.to_s}")
      | #{season.year}

.ui.relaxed.divided.list
  - @events.each do |event|
    .item
      .right.floated.compact.ui
        - if event.races.count > 0
          .ui.dropdown
            .ui.large.labeled.icon.green.button
              .text Results
              = semantic_icon 'dropdown'
            .menu
              .item =link_to "Overall Results", event_results_path(event)
              .item =link_to "Pit Stops", event_stops_path(event)
              - if event.laptimes_csv_file_exists?
                .item =link_to "Download Lap times (CSV)", event_laptimes_path(event, format: :csv)
        = link_to "View Team List", event_teams_path(event), class: 'ui small basic button'
        - if event.reservable_items.count > 0
          = link_to "Reservations", event_reservables_path(event), class: 'ui small basic button'
        - if current_user.present?
          .ui.dropdown
            .ui.red.inverted.button
              | Admin
              = semantic_icon 'dropdown'
            .menu
              .item =link_to "Registered Drivers List", event_driver_registrations_path(event)
              .item =link_to "Registered Drivers List (CSV)", event_driver_registrations_path(event, format: 'csv')
      .content
        =semantic_icon 'circular calendar'
        .header = event.track
        .meta #{event.start_date.to_s(:long)} to #{event.stop_date.to_s(:long)}
        .ui.tiny.horizontal.divided.list
          - previous_race = nil
          -event.races.each do |race|
            - unless race.qualifying?
              .item
                .header=race.name
                .ui.tiny.bulleted.list
                  - if previous_race.present?
                    = link_to "Grid Sheet", grid_race_results_path(previous_race), class: 'item'
                  - unless race.qualifying?
                    = link_to "Results", race_results_path(race), class: 'item'
            - previous_race = race
  = link_to "Season Standings", season_results_path(@year), class: 'ui large blue button'

app/views/events/stops.slim
h1.ui.block.header
  = semantic_icon('large circular invertered calendar')
  .content
    = "Pit Outs for #{@event.track}"
    .sub.header
      | #{@registrations.count} registrations

-@event.races.each do |race|
  h2.ui.block.header
    = semantic_icon('large circular invertered calendar')
    .content
      = "#{race.name}"
      .sub.header
        | #{@registrations.count} registrations for #{race.start_time.to_date.to_s(:long)}

  table#scan_list.ui.celled.table
    thead
      tr
        th Car #
        - race.hour_timestamps.each do |timestamp|
          - time = Time.at(timestamp)
          - hour = time.in_time_zone(@event.time_zone).hour
          th
            - if hour.to_i < 12
              = "#{hour}AM"
            - elsif hour.to_i == 12
              | 12PM
            - else
              = "#{hour - 12}PM"
    tbody
      - @registrations.each do |registration|
        tr(class="#{"myteam" if current_driver && current_driver.team == registration.team}")
          th
            .car_number ="##{registration.car_number}"
            .team_name = "#{registration.team}"

            - scans = registration.scans.out.for_race(race).to_a
            - race.hour_timestamps.each do |timestamp|
              - next_hour = timestamp + 3600
              - time = Time.at(timestamp)
              - hour = time.in_time_zone(@event.time_zone).hour
              td
                ul.ui.list
                  - this_hour_scans = scans.select { |scan| scan.created_at.to_i < next_hour }
                  - scans.delete_if { |scan| scan.created_at.to_i < next_hour }
                  - this_hour_scans.each do |scan|
                    - if scan.short_stop?
                      li.item.short_stop
                        .driver = link_to scan.driver_name, scan
                        .time = scan.formatted_time
                    - else
                      li.item
                        .driver = link_to scan.driver_name, scan
                        .time = scan.formatted_time

  a.ui.labeled.icon.button href="#{events_path}"
    = semantic_icon 'left arrow'
    | Back

.short_stop
  | Stops in red are short stops and do not count against the minimum pit count.

app/views/events/teams.html.slim
h1.ui.block.header
  = semantic_icon('large circular invertered calendar')
  .content
    = "#{@event.track}"
    .sub.header
      | #{@registrations.count} registrations for #{@event.start_date.to_s(:long)}


= form_tag event_registrations_path(@event), method: :post do
  - if current_user.present?
    = submit_tag "Save", class: "ui primary button"
  - if current_user.present?
    .ui.left.floated Car Class:
  .ui.relaxed.divided.list
    - @registrations.each do |registration|
      .item(data-class=registration.car_class)
        .right.floated.compact.ui
          = registration.car.car_type
          - if current_user.present?
            .verified(style="text-align: right")
              label
                | Verified?
                = check_box_tag "registrations[#{registration.id}][verified]", true, registration.verified?
        .content
          - if current_user.present?
            .ui.left.floated = text_field_tag "registrations[#{registration.id}][car_class]", registration.car_class, size: 2
          - elsif registration.car_class.present?
            .ui.left.floated.black.button = registration.car_class
          .ui.horizontal.statistic
            .value = "##{registration.car_number}"
            .label = registration.team

  - if current_user.present?
    = submit_tag "Save", class: "ui primary button"