config/routes.rb
require 'sidekiq/web'

Aer::Application.routes.draw do
  use_doorkeeper

  devise_for :drivers, controllers: { registrations: "driver/registrations" }
  devise_for :users

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Aer::API => '/api', as: 'api'

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
    resources :sms_messages, only: [:new, :create, :destroy] do
      member do
        post :resend
      end
      collection do
        post :clear_pending
      end
    end
  end

  authenticate :driver do
    resources :teams, only: [:index] do
      post "select", on: :member
    end
    resources :drivers, only: [:show] do
      collection do
        get :autocomplete
      end
    end
    resource :team, except: [:destroy]
    resources :cars
    resources :registrations, only: [:create, :show, :destroy, :update] do
      resources :payments, only: [:create]
      resources :drivers, only: [:index, :create, :destroy], module: 'registrations'
      resources :reservables, only: [:index, :show] do
        resource :reservation, only: [:create, :destroy]
      end
    end
  end

  resources :drivers, only: [:index] do
    member do
      get :barcode
    end
  end

  resources :seasons, only: [] do
    resources :results, only: [:index]
  end

  resources :events, only: [:index] do
    get :teams
    get :stops
    resources :laptimes, only: [:index]
    resources :races, only: [:index]
    resources :results, only: [:index]
    resources :reservables, only: [:index, :show]
    post :registrations

    authenticate :user do
      resources :driver_registrations, only: [:index]
    end
  end

  resources :races, only: [] do
    resources :unknown_drivers, only: [:index]
    resources :results, only: [:index, :create] do
      collection do
        get :grid
        post :grid, action: 'update_grid'
        get :preview
        post :preview, action: 'update_preview'
        post :generate
      end
    end
  end

  resources :scans, only: [:update]

  authenticate :user do
    resources :registrations, only: [] do
      resources :scans, only: [:new]
    end
  end

  resources :scans, only: [:create, :show] do
    post :analyze, on: :member
    post :mock_pit, on: :member
    post :violation, on: :member
  end

  resources :rfid_reads, only: [:create, :index, :show]

  get '/live', to: 'live#show', as: 'live'

  get '/scan/:event/:pit/:car/:driver', :to => 'scan#create'
  post '/scan/:event/:pit/:car/:driver', :to => 'scan#create'

  get '/cars/:id/barcode', :to => 'car#barcode'
  get '/qualifying', :to => 'qualifying#index'

  get '/orbits/export', :to => 'orbits#export'

  post '/rfidtest', to: 'rfidtests#create'

  root to: redirect("/team")
end

app/controllers/reservables_controller.rb
class ReservablesController < ApplicationController
  before_filter { @event        = event }
  before_filter { @registration = registration }

  def index
    @reservable_items = @event.reservable_items

    if @registration.present?
      @show_item = ->(reservable_item) {
        registration_reservable_path(@registration, reservable_item)
      }
    else
      @show_item = ->(reservable_item) {
        event_reservable_path(@event, reservable_item)
      }
    end
  end

  def show
    @reservable_item = ReservableItem.find(params[:id])
    @reservations = @reservable_item.reservations
  end

  private
  def event
    @event ||=
      if (params[:event_id])
        Event.friendly.find(params[:event_id])
      elsif registration
        registration.event
      end

    @event
  end

  def registration
    @registration ||= Registration.find(params[:registration_id]) if params[:registration_id]
  end
end

app/views/reservables/index.slim
h1.ui.block.header
  = semantic_icon('large circular invertered calendar')
  .content
    = "Reservable Items for #{@event.track}"

-if @registration.present?
  h2.ui.header Click below to reserve:
-else
  h2.ui.header Click below to view reservations:
.ui.relaxed.divided.list
  -@reservable_items.each do |reservable_item|
    .item
      .right.floated.compact.ui
      .content
        .header
          a.ui.large.green.button(href="#{@show_item.call(reservable_item)}")= reservable_item.name

- if @registration.present?
  a.ui.labeled.icon.button href="#{registration_path(@registration)}"
    = semantic_icon 'left arrow'
    | Back

app/views/reservables/show.slim
h1.ui.block.header
  = semantic_icon('large circular invertered calendar')
  .content
    = "Reservations for #{@reservable_item.name} at #{@event}"

.ui.segment
  - if @reservable_item.image.present?
    = image_tag @reservable_item.image.url

  - if @reservable_item.description.present?
    p=@reservable_item.description

  h3.ui.header Current Reservations:
  .ui.relaxed.divided.list
    -@reservations.each_pair do |spot_number, registrations|
      .item
        - if @registration.present?
          .right.floated.compact.ui
            - if !@registration.reserved?(@reservable_item)
              = link_to registration_reservable_reservation_path(@registration, @reservable_item, item_number: spot_number), method: :post, class: "ui button" do
                | Reserve ##{spot_number}
                - if @reservable_item.item_price_in_cents > 0
                  = " (#{number_to_currency(@reservable_item.item_price_in_cents / 100)})"

            - elsif @registration.reservation_number(@reservable_item) == spot_number
              = link_to "Remove Reservation", registration_reservable_reservation_path(@registration, @reservable_item), method: :delete, class: 'ui red button'
        .content
          .header
            = "##{spot_number}"
          .meta
            - if registrations.count == 0
              .em Not yet reserved
            - else
              ul.ui.list
                - registrations.each do |registration|
                  li= "##{registration.car_number} #{registration.team}"

- if @registration.present?
  a.ui.labeled.icon.button href="#{registration_path(@registration)}"
    = semantic_icon 'left arrow'
    | Back