config/routes.rb
require 'sidekiq/web'

Aer::Application.routes.draw do
  use_doorkeeper

  devise_for :drivers, controllers: { registrations: "driver/registrations" }
  devise_for :users

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Aer::API => '/api', as: 'api'

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
    resources :sms_messages, only: [:new, :create, :destroy] do
      member do
        post :resend
      end
      collection do
        post :clear_pending
      end
    end
  end

  authenticate :driver do
    resources :teams, only: [:index] do
      post "select", on: :member
    end
    resources :drivers, only: [:show] do
      collection do
        get :autocomplete
      end
    end
    resource :team, except: [:destroy]
    resources :cars
    resources :registrations, only: [:create, :show, :destroy, :update] do
      resources :payments, only: [:create]
      resources :drivers, only: [:index, :create, :destroy], module: 'registrations'
      resources :reservables, only: [:index, :show] do
        resource :reservation, only: [:create, :destroy]
      end
    end
  end

  resources :drivers, only: [:index] do
    member do
      get :barcode
    end
  end

  resources :seasons, only: [] do
    resources :results, only: [:index]
  end

  resources :events, only: [:index] do
    get :teams
    get :stops
    resources :laptimes, only: [:index]
    resources :races, only: [:index]
    resources :results, only: [:index]
    resources :reservables, only: [:index, :show]
    post :registrations

    authenticate :user do
      resources :driver_registrations, only: [:index]
    end
  end

  resources :races, only: [] do
    resources :unknown_drivers, only: [:index]
    resources :results, only: [:index, :create] do
      collection do
        get :grid
        post :grid, action: 'update_grid'
        get :preview
        post :preview, action: 'update_preview'
        post :generate
      end
    end
  end

  resources :scans, only: [:update]

  authenticate :user do
    resources :registrations, only: [] do
      resources :scans, only: [:new]
    end
  end

  resources :scans, only: [:create, :show] do
    post :analyze, on: :member
    post :mock_pit, on: :member
    post :violation, on: :member
  end

  resources :rfid_reads, only: [:create, :index, :show]

  get '/live', to: 'live#show', as: 'live'

  get '/scan/:event/:pit/:car/:driver', :to => 'scan#create'
  post '/scan/:event/:pit/:car/:driver', :to => 'scan#create'

  get '/cars/:id/barcode', :to => 'car#barcode'
  get '/qualifying', :to => 'qualifying#index'

  get '/orbits/export', :to => 'orbits#export'

  post '/rfidtest', to: 'rfidtests#create'

  root to: redirect("/team")
end

app/models/car.rb
# create_table :cars, force: :cascade do |t|
#   t.string   :barcode,              limit: 255
#   t.datetime :created_at
#   t.datetime :updated_at
#   t.string   :make,                 limit: 255
#   t.string   :model,                limit: 255
#   t.integer  :captain_id,           limit: 4
#   t.string   :passcode,             limit: 255
#   t.integer  :year,                 limit: 4
#   t.integer  :team_id,              limit: 4
#   t.string   :color,                limit: 25
#   t.string   :transponder_number,   limit: 25
#   t.integer  :season_id,            limit: 4
#   t.string   :number,               limit: 5
#   t.integer  :tech_inspection_year, limit: 4
# end
#
# add_index :cars, [:barcode], name: :index_cars_on_barcode, using: :btree

class Car < ActiveRecord::Base
  include BarcodeCapable

  def self.barcode_offset
    20000_00000_00000_00000_000 # 23 digits (24 total with 'C' prepended)
  end

  has_paper_trail

  belongs_to :captain, class_name: 'Driver'
  belongs_to :team
  belongs_to :season

  has_many :registrations, dependent: :destroy

  has_many :scans,   through: :registrations
  has_many :events,  through: :registrations

  has_many :violations, through: :scans

  delegate :drivers, to: :team

  scope :current, -> { where(season_id: Season.current.id) }

  validates :number, :year, :make, :model, :team, presence: true

  validates_uniqueness_of :number, scope: :season_id, allow_nil: false, message: "for car is already taken for this season. :'-( Choose another car number."

  before_validation :assign_to_current_season, if: ->(car) { car.season.blank? }
  before_save :reset_transponder_rentals, if: ->(car) { car.transponder_number_changed? and car.transponder_number_was.blank? }

  def self.find_by_barcode(barcode)
    where(barcode: barcode).first
  end

  def latest_registration
    self.registrations.order("created_at DESC").first
  end

  def to_s
    "##{self.number} #{car_type}"
  end

  def car_number
    number
  end

  def name
    "#{to_s} (#{self.season_id})"
  end

  def rally_baby?
    team.name =~ /rally baby/i
  end

  def team_name
    team.name
  end

  def car_type
    "#{self.year} #{self.make} #{self.model}"
  end

  def registered_for?(event)
    self.registration_ids.include?(event.id)
  end

  def registration_for(event)
    Registration.unscoped.where(car_id: self.id, event_id: event.id).first
  end

  def assign_to_current_season
    self.season = Season.current
  end

  def reset_transponder_rentals
    Registration.unscoped.where(car_id: self.id).future.not_ready.update_all(transponder_rental: false)
  end

  rails_admin do
    show do
      field :barcode do
        formatted_value do
          bindings[:view].link_to bindings[:object].barcode, "/cars/#{bindings[:object].id}/barcode"
        end
      end

      include_all_fields
    end

    list do
      filters [:number, :team, :season_id]

      field :barcode do
        formatted_value do
          bindings[:view].link_to bindings[:object].barcode, "/cars/#{bindings[:object].id}/barcode"
        end
      end
      field :number
      field :year
      field :make
      field :model
      field :team
      field :captain
      field :transponder_number
      field :season_id, :enum do
        filterable true
        enum { (2015..Date.today.year) }
      end

      exclude_fields :id, :created_at, :updated_at
    end
  end
end

app/controllers/car_controller.rb
class CarController < ApplicationController
  def ssl_required?
    false
  end

  def sell
    render layout: 'sell'
  end

  def index
    cols = [:car_number, :info, :barcode]
    cars = Car.select(cols).order(:car_number)
    list = ''
    cars.each{ |r| list += r.attributes.except(:id).values.to_csv }
    render plain: list
  end

  def barcode
    @car = Car.find(params[:id])
    @car.generate_barcode unless @car.barcode_exists?

    render layout: false
  end

  def show
    respond_to do |format|
      format.html
      format.pdf do
        render :pdf => "show"
      end
    end
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_filter :fetch_team

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    @car.captain = current_driver
    @car.team = @team
    if @car.save
      flash[:notice] = "Your car was successfully added to your team."
      redirect_to team_path
    else
      render action: 'new'
    end
  end

  def index
    @registrations = Event.current.registrations.sort { |a,b| a.car_number.to_i <=> b.car_number.to_i }
  end

  def edit
    @car = @team.cars.find(params[:id])
  end

  def update
    @car = @team.cars.find(params[:id])

    if @car.update_attributes(car_params)
      flash[:success] = "Your car was modified"
      redirect_to team_path
    else
      render action: 'edit'
    end
  end

  def show
    @car = @team.cars.find(params[:id])
    @events = Event.registerable.all

    @registrations = @car.registrations.where(event_id: @events.map(&:id)).all
  end

  def destroy
    @car = @team.cars.find(params[:id])
    if @car.registrations.count == 0
      @car.destroy
      flash[:success] = "Car deleted. You monster, you."
    end
    redirect_to team_path # Silent failure, let them contact us if this isn't working
  end

  private
  def fetch_team
    @team = current_driver.team
    if @team.nil?
      flash[:error] = "You'll need to join or create a team before you can continue."
      redirect_to teams_path
    end
  end

  def car_params
    params.require(:car).permit(:number, :color, :year, :make, :model, :transponder_number)
  end
end

app/views/cars/_form_fields.html.slim
- if f.object.errors.any?
  .ui.message
    .header Something went wrong:
    ul.list
      - f.object.errors.full_messages.each do |msg|
        li= msg

.field
  .ui.labeled.input
    .ui.label Car Number
    = f.text_field :number, data: { validate: 'required' }
    .ui.corner.label = semantic_icon 'asterisk'
  .ui.hidden.divider

- { color: 'Enter color', year: 'Enter year of car', make: 'Enter make', model: 'Enter model' }.each do |input, placeholder|
  .field
    .ui.labeled.input
      .ui.label = f.label input
      = f.text_field input, placeholder: placeholder, data: { validate: 'required' }
      .ui.corner.label = semantic_icon 'asterisk'
  .ui.hidden.divider

.field
  .ui.labeled.input
    .ui.label = f.label :transponder_number
    = f.text_field :transponder_number, placeholder: "Enter Transponder # (optional)"
.ui.hidden.divider

app/views/cars/edit.html.slim
.ui.block.header
  = semantic_icon('large circular invertered car')
  .content
    | Modify your car
    .sub.header
      | Make changes to your car with 
      = @team

.ui.segment.raised
  = form_for @car, html: { class: 'ui form' } do |f|
    = render "form_fields", f: f

    = f.submit "Save car", class: 'ui submit primary button'

app/views/cars/index.slim
table.ui.striped.very.compact.small.table
  thead
    th
    th Car
    th Team
    th ?
  tbody
    - @registrations.each do |registration|
      tr
        td.collapsing
          input.ui.checkbox(type='checkbox')
        td.collapsing
          = registration.car_number
        td
          = registration.team
        td
          input.ui.input(size="100")

app/views/cars/new.html.slim
.ui.block.header
  = semantic_icon('large circular invertered car')
  .content
    | Add a Car
    .sub.header
      | Register a new car with 
      = @team

.ui.segment.raised
  = form_for @car, html: { class: 'ui form' } do |f|
    = render "form_fields", f: f

    = f.submit "Save car", class: 'ui submit primary button'

app/views/cars/show.html.slim
h1.ui.block.header
  - if @car.team.rally_baby?
    = semantic_icon('large red circular invertered loading car')
  - else
    = semantic_icon('large circular invertered car')
  .content
    = @car.team.name
    .sub.header
      = "##{@car.number} #{@car.car_type}"

h2.ui.dividing.header Events
- @events.each do |event|
  .ui.raised.segment
    .content
      .right.floated.compact.ui.basic.segment
        - if registration = @car.registration_for(event)
          - if registration.paid_in_full?
            = link_to "Manage Registration", registration_path(registration), class: 'ui green button'
          - else
            = link_to "Payment Due: #{number_to_currency(registration.amount_due_dollars)}", registration_path(registration), class: 'ui button red'
        - else
          = form_tag registrations_path, id: "register_for_event_#{event.id}" do
            = hidden_field_tag 'registration[event_id]', event.id
            = hidden_field_tag 'registration[car_id]', @car.id
            = submit_tag "Register to race (#{number_to_currency(event.price_in_cents / 100.0)})", class: 'ui blue button'
      h2.ui.header
        = semantic_icon 'road'
        .content
          = event.track
      .meta #{event.start_date.to_s(:long)} to #{event.stop_date.to_s(:long)}
      - if registration
        .ui.segment
          h5.ui.header Registered Drivers (<a href="#{registration_drivers_path(registration)}">manage</a>)
          - if registration.driver_registrations.count == 0
            | No drivers yet
          - else
            .ui.relaxed.horizontal.list(style="list-style-type: none;")
              - registration.driver_registrations.each do |driver_registration|
                .item
                  - if @car.team.rally_baby?
                    = semantic_icon 'cocktail'
                  - else
                    = semantic_icon 'user'
                  .content
                    .header #{driver_registration.driver.full_name }
                    .meta Driver
                    .description
                      = pluralize(driver_registration.driver.lifetime_lap_count, "lifetime lap")



.ui.divider

- if @car.registrations.count == 0
  = link_to car_path(@car), method: :delete, class: 'ui labeled right floated icon button red' do
    = semantic_icon 'close'
    | Remove Car

= link_to edit_car_path(@car), class: 'ui labeled right floated icon button' do
  = semantic_icon 'edit'
  | Edit Car

a.ui.labeled.icon.button href="#{team_path}"
  = semantic_icon 'left arrow'
  | Back